language: node_js
node_js:
  - '0.10'
addons:
  sauce_connect: true
  code_climate:
    repo_token: ef1939588b1230f06a704858afb754c6434c41602b7997aee180b8afe30b34b3
install:
  - 'npm install'
  - 'npm install -g bower grunt-cli'
  - 'bower install'
script:
  - 'grunt test'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && grunt e2e-sauce || false'
after_script:
  - codeclimate < test/reports/coverage/*/lcov.info
env:
  global:
    - secure: aDsdCx654T824NbL1KNxuIBocnjbJAO6dSF2wntRQfBs4BTXqZ5ap6ssajvYMps/VkoG7KYOrLB5PyXtWLF4zrmOIUZnCd/bnAf42GKgI3ORhG7jxsyeKU3wObpyEhGZ3+fkw8m07Vrk35U6kfiR2Jlud6DXCDqFjZ2Kq4iaxfgk4uKOzYPeLVXQqzlgya59rudy4yy1Odxy+CmGsqXcfHSu4Kaf6hOrsVw9Kd/SufRfuRvP3/9ooGSfpjJWBdmAvUPRQ/aw3VGkjtqE4RxREX5/6P9ex5LjeMgP+XQogfxLGRM7jdeXAlcRytYvxA5eUG/5LcLESRkIRyuYdQgjnmm+eneydI2OkzR2Ac7rJ7WZvvFYXlWbGOQU+EkgBzodl+VRAt/qG7CMjrAabukHD57nlo4bv64E1ZS/1xyvVpnyzAA4fKZDXfsluLsN87QyE3odf9CRO8t2evnVHvf17OzrTzcErf6dJW4FpbBhSz5dL8Q+x4C6sAVFrBtjBJX2qADlGSVL5kEabMus0u2eeKvJiaZqVCH/Sgz+my5XRv2C76sWggztHEiBWnBUqkvFJXZfa/OuREBgJbLOF+Ag9KxeMYLFK5CaZvP3g2VE/BTJPwgJs89LVJTsPraFeoZoEYhD3W1Q8mQLCpiPkKN07GcSKXWc0tzBj1uOqdC5YTg=
    - secure: ToNkdHVwRiwZJusSaobQcj6gIxaSACkLUK9m3XUElOFJkeTHWfMXcbmBUbjQlIcUTcZ5uB3OJDHnu4rR4iibT8k2B6o/52u2CZtkVvDZNdZ2x9DTUeSbWguBMI+ifm+fTCLXNqVbYz/eSxikTnH7WyWVqky23vUsJboqxLd9Bqh2RnSeUMpMzOIXtMkDpuqQgTT0iexVk4WRLc2ZxnM61/4HF1lJP2uaPibou8dR5Xi8p5OP2iFKM+7+PTKx0veU6ea9305Ti7VLfXGF0biK8kcUEjdwVtjP+vgxobiyz2mSyLhYiHm+9diToCCdtYTD80VPTC0+JsPBaB9qeF6qwvzWjcptEFwkCW3sQ+EBtJ6i+IKJLdpzvGgINhGBrDx4264l2zCwF/ptE2rOSaZ5Cf99QrF46vd06T9ThLTM/uyWZxhZzp66fhEmls15wzk9Apb1sq6UdNyrdHUjkqFHZ22U920ERjxAkFRTq3vyHbpOVDxanKMIFILX7Xe7Kd5Yvo5wJy+SPrE3Ozw9TZ4gsvaAFJGi/Vq7G26VGwRrboHz7CS/sUmJIhibE7/g7DPm5zvdjQVN9PVKuibuaybZZ5x5xNsy/2+8QHoH4WTmiUSvVT1vQKTTYf2DQgBEhlp+/HhbF7UEVczAbittR8s/cpj37FR+N5La/NfD92x0scM=
sudo: false
