language: node_js
node_js:
  - '0.10'
addons:
  sauce_connect: true
  code_climate:
    repo_token: ef1939588b1230f06a704858afb754c6434c41602b7997aee180b8afe30b34b3
before_install:
  - gem install compass
install:
  - 'npm install'
  - 'npm install -g bower grunt-cli'
  - 'bower install'
script:
  - 'grunt test'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && grunt e2e-sauce || false'
after_script:
  - codeclimate < test/reports/coverage/*/lcov.info
env:
  global:
    - secure:
    - secure:
sudo: false
